package gui;

import javax.swing.*;
import java.awt.*;

public class UIAbout extends JPanel {

    private JTabbedPane trythis;
    private JLabel headline;
    private JLabel description1;
    private JLabel author;

    public UIAbout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        headline = new JLabel();
        description1 = new JLabel();
        author = new JLabel();
        GroupLayout layout = new GroupLayout(this);

        setEnabled(false);

        headline.setFont(new Font("Nimbus", Font.PLAIN, 20 ));
        headline.setText("SVO Detect v.1.0.");

        description1.setFont(new Font("Nimbus", Font.PLAIN, 14 ));
        description1.setText("Burpsuite PlugIn for Detection and Evaluation of Session Variable Overloading");


        author.setFont(new Font("Nimbus", Font.PLAIN, 14 ));
        author.setText("© 2020, by Hanna Algedri ");

        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(headline)
                                        .addComponent(author))
                                       // .addComponent(explaination2))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headline)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(author)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                //.addComponent(explaination2)
                                //.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addContainerGap())
        );

    }

}

